spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        format_sql: true

  liquibase:
    enabled: true



server:
  port: 8081
